# Generated by Django 4.2.29 on 2026-03-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtr_id', models.CharField(max_length=20, unique=True, verbose_name='DTR ID')),
                ('team_id', models.CharField(default='TEAM-A', max_length=20)),
                ('date', models.DateField()),
                ('time_in', models.CharField(default='-', max_length=10)),
                ('time_out', models.CharField(default='-', max_length=10)),
                ('break_minutes', models.IntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('On Leave', 'On Leave')], default='Present', max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dtr_records', to='payroll.employee')),
            ],
            options={
                'verbose_name': 'DTR Record',
                'verbose_name_plural': 'DTR Records',
                'ordering': ['-date', 'dtr_id'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
