# Generated by Django 4.2.30 on 2026-04-20 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dtr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtrrecord',
            options={'ordering': ['-date', 'dtr_id']},
        ),
        migrations.AddField(
            model_name='dtrrecord',
            name='adjustment_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtrrecord',
            name='adjustment_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dtrrecord',
            name='auto_clocked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dtrrecord',
            name='requires_adjustment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dtrrecord',
            name='dtr_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
