# Generated by Django 4.2.29 on 2026-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=20, unique=True, verbose_name='Material ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=30)),
                ('min_stock', models.IntegerField(default=0, verbose_name='Minimum Stock Level')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price (₱)')),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['material_id'],
            },
        ),
    ]
