# Generated by Django 4.2.30 on 2026-04-20 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_id']},
        ),
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={'ordering': ['-period', 'payroll_id']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='deductions',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='net_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='payroll_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='period',
            field=models.CharField(max_length=7),
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_id', models.CharField(max_length=20, unique=True)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='payroll.employee')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pay_period_end'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePayrollProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_exemptions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sss_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('philhealth_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagibig_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pay_type', models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly')], default='hourly', max_length=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('missed_deadline', 'Missed Deadline'), ('late', 'Late'), ('advance', 'Cash Advance'), ('sss', 'SSS'), ('philhealth', 'PhilHealth'), ('pagibig', 'Pag-IBIG'), ('tax', 'Tax'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deductions', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='payroll.payrollrun')),
            ],
        ),
    ]
