# Generated by Django 4.2.29 on 2026-03-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20, unique=True, verbose_name='Project ID')),
                ('name', models.CharField(max_length=200)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage 0-100')),
                ('status', models.CharField(default='Started', max_length=30)),
                ('deadline', models.DateField()),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=20, unique=True, verbose_name='Task ID')),
                ('task_name', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(help_text='Worker name', max_length=100)),
                ('assigned_by', models.CharField(help_text='Role/name of assigner', max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('deadline', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='production.project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_date', 'task_id'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_id', models.CharField(max_length=20, unique=True, verbose_name='QC ID')),
                ('inspection_item', models.CharField(max_length=200)),
                ('inspector', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], default='Pass', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production.project')),
            ],
            options={
                'verbose_name': 'Quality Check',
                'verbose_name_plural': 'Quality Checks',
                'ordering': ['-date', 'qc_id'],
            },
        ),
    ]
