# Generated by Django 4.2.29 on 2026-03-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_qualitycheck_task_alter_task_status_budgetrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitycheck',
            name='task',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='BudgetRequest',
        ),
    ]
