# Generated by Django 4.2.30 on 2026-04-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_project_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_id']},
        ),
        migrations.AlterModelOptions(
            name='qualitycheck',
            options={'ordering': ['-date', 'qc_id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_date', 'task_id']},
        ),
        migrations.AddField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('Awaiting DP', 'Awaiting Down Payment'), ('DP Received', 'Down Payment Received'), ('Fully Paid', 'Fully Paid')], default='Awaiting DP', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_flag',
            field=models.CharField(choices=[('On Track', 'On Track'), ('Warning', 'Warning'), ('Review', 'Performance Review'), ('Disciplinary', 'Disciplinary Action')], default='On Track', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='missed_deadline_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='qc_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
